#ifndef UART_CONFIG_H_
#define UART_CONFIG_H_

//OPTIONS:
/*
 * UART_FIVE_BITS
 * UART_SIX_BITS
 * UART_SEVEN_BITS
 * UART_EIGHT_BITS
 * UART_NINE_BITS
 */
#define UART_DATA_BITS		UART_EIGHT_BITS

//OPTIONS:
/*
 * UART_SIMPLEX
 * UART_DUPLEX
 */
#define UART_DIRECTION		UART_DUPLEX

//OPTIONS:
/*
 * UART_MASTER/UART_TRANSMITTER
 * UART_SLAVE/UART_RECIEVER
 */
#define UART_MASTER_SELECT 	UART_MASTER

//OPTIONS:
/*
 * UART_INTERRUPT_OFF
 * UART_INTERRUPT_ON
 */
#define UART_INTERRUPT		UART_INTERRUPT_ON

//OPTIONS:
/*
 * UART_ASYNC
 * UART_SYNC
 */
#define UART_MODE			UART_ASYNC

#if(UART_MODE == UART_ASYNC)
#define UART_BAUD_RATE		9600
//#define UART_BAUD_RATE		57600
#endif

//OPTIONS:
/*
 * UART_NO_PARITY
 * UART_EVEN_PARITY
 * UART_ODD_PARITY
 */
#define UART_PARITY			UART_NO_PARITY

//OPTIONS:
/*
 * UART_ONE_STOP
 * UART_TWO_STOPS
 */
#define UART_STOP			UART_ONE_STOP

#define UART_TERMINATION_CHAR	'\0'

#endif /* UART_CONFIG_H_ */
