#include "SEV_SEG.h"

STD_Type HAL_SEV_SEG_u8DisplayNo(u8 LOC_u8No)
{
	STD_Type LOC_u8ReturnValue = E_NOT_OK;
	if(LOC_u8No <= MAX_SEV_SEG_NO)
	{
		u8 LOC_u8Units = LOC_u8No % DIGIT_DIVIDEND;
		u8 LOC_u8Tens = LOC_u8No / DIGIT_DIVIDEND;

		LOC_u8ReturnValue = MCAL_DIO_u8SetPortDirection(SEV_SEG_SEGMENT_WRITE_PORT,ALL_ONES);
		LOC_u8ReturnValue = MCAL_DIO_u8SetPinDirection(SEV_SEG_SEGMENT_1_ENABLE_PORT,SEV_SEG_SEGMENT_1_ENABLE_PIN,DIO_OUTPUT);
		LOC_u8ReturnValue = MCAL_DIO_u8SetPinValue(SEV_SEG_SEGMENT_1_ENABLE_PORT,SEV_SEG_SEGMENT_1_ENABLE_PIN,DIO_HIGH);
		LOC_u8ReturnValue = MCAL_DIO_u8SetPortValue(SEV_SEG_SEGMENT_WRITE_PORT, (LOC_u8Units << SEGMENT_SHIFT));
		_delay_ms(1);
		LOC_u8ReturnValue = MCAL_DIO_u8SetPinValue(SEV_SEG_SEGMENT_1_ENABLE_PORT,SEV_SEG_SEGMENT_1_ENABLE_PIN,DIO_LOW);

		LOC_u8ReturnValue = MCAL_DIO_u8SetPinDirection(SEV_SEG_SEGMENT_2_ENABLE_PORT,SEV_SEG_SEGMENT_2_ENABLE_PIN,DIO_OUTPUT);
		LOC_u8ReturnValue = MCAL_DIO_u8SetPinValue(SEV_SEG_SEGMENT_2_ENABLE_PORT,SEV_SEG_SEGMENT_2_ENABLE_PIN,DIO_HIGH);
		LOC_u8ReturnValue = MCAL_DIO_u8SetPortValue(SEV_SEG_SEGMENT_WRITE_PORT, (LOC_u8Tens << SEGMENT_SHIFT) );
		_delay_ms(1);
		LOC_u8ReturnValue = MCAL_DIO_u8SetPinValue(SEV_SEG_SEGMENT_2_ENABLE_PORT,SEV_SEG_SEGMENT_2_ENABLE_PIN,DIO_LOW);
		//LOC_u8ReturnValue = MCAL_DIO_u8SetPinValue(SEV_SEG_SEGMENT_1_ENABLE_PORT,SEV_SEG_SEGMENT_1_ENABLE_PIN,DIO_HIGH);
	}
	else
	{
		//Do Nothing
	}
	return LOC_u8ReturnValue;
}
