#ifndef DC_MOTOR_CONFIG_H_
#define DC_MOTOR_CONFIG_H_

#define DC_MOTOR0_IN1_PORT	DIO_PortA
#define DC_MOTOR0_IN1_PIN	Pin0
#define DC_MOTOR0_IN2_PORT	DIO_PortA
#define DC_MOTOR0_IN2_PIN	Pin1
#define DC_MOTOR0_EN_PORT	DIO_PortB
#define DC_MOTOR0_EN_PIN	Pin3

#define DC_MOTOR1_IN1_PORT	DIO_PortA
#define DC_MOTOR1_IN1_PIN	Pin2
#define DC_MOTOR1_IN2_PORT	DIO_PortA
#define DC_MOTOR1_IN2_PIN	Pin3
#define DC_MOTOR1_EN_PORT	DIO_PortD
#define DC_MOTOR1_EN_PIN	Pin4

#define DC_MOTOR1_PWM_FREQUENCY	50

#define DC_MOTOR2_IN1_PORT	DIO_PortD
#define DC_MOTOR2_IN1_PIN	Pin2
#define DC_MOTOR2_IN2_PORT	DIO_PortD
#define DC_MOTOR2_IN2_PIN	Pin3
#define DC_MOTOR2_EN_PORT	DIO_PortD
#define DC_MOTOR2_EN_PIN	Pin6


#endif /* DC_MOTOR_CONFIG_H_ */